---
- name: Vérifier et utiliser les secrets Vault dans le script
  hosts: localhost
  gather_facts: no

  vars:
    # Vous pouvez définir vault_addr directement ici si vous ne l'avez pas dans l'environnement
    vault_addr: "{{ lookup('ansible.builtin.env', 'VAULT_ADDR') | default('http://10.10.150.2:8200') }}"  # Utilise VAULT_ADDR de l'environnement ou valeur par défaut
    vault_token: "{{ lookup('env', 'VAULT_TOKEN') }}"  # Token Vault depuis une variable d'environnement ou directement dans le fichier
    vault_path: "secret/data/proxmox/parameters"  # Chemin des secrets dans Vault

  tasks:
    # Vérifier que les variables sont bien définies
    - name: Vérifier si vault_addr et vault_token sont définis
      fail:
        msg: "Les variables vault_addr et vault_token doivent être définies."
      when: vault_addr is not defined or vault_token is not defined

    # Récupérer les secrets depuis Vault
    - name: Récupérer les secrets depuis Vault
      community.hashi_vault.vault_read:
        url: "{{ vault_addr }}"
        token: "{{ vault_token }}"
        path: "{{ vault_path }}"
      register: vault_secrets

    # Vérifier la récupération des secrets
    - name: Vérifier si les secrets ont été récupérés
      fail:
        msg: "Impossible de récupérer les secrets depuis Vault."
      when: vault_secrets.failed

    # Afficher les secrets récupérés
    - name: Afficher les secrets récupérés
      debug:
        var: vault_secrets.data.data

    # Définir les variables sensibles à partir des secrets récupérés
    - name: Définir les variables à partir des secrets Vault
      set_fact:
        proxmox_source_environment: "{{ vault_secrets.data.data.data.proxmox_source_environment }}"
        proxmox_destination_environment: "{{ vault_secrets.data.data.data.proxmox_destination_environment }}"
        ssh_host: "{{ vault_secrets.data.data.data.ssh_host }}"
        vault_addr: "{{ vault_secrets.data.data.data.vault_addr }}"  # Notez que vous pouvez redéfinir cette variable si nécessaire
        vault_token: "{{ vault_secrets.data.data.data.vault_token }}"  # Idem pour le token

    # Afficher les valeurs des variables définies
    - name: Vérifier que les variables sont bien définies
      debug:
        msg: "Proxmox Source Environment: {{ proxmox_source_environment }}, Proxmox Destination Environment: {{ proxmox_destination_environment }}, SSH Host: {{ ssh_host }}"

    # Exemple de tâche avec les secrets récupérés (ici une simple tâche pour tester la connectivité SSH)
    - name: Tester la connectivité SSH au serveur distant
      ansible.builtin.ping:
      delegate_to: "{{ ssh_host }}"
      when: ssh_host is defined

    # Exemple d'utilisation d'une variable dans une commande (exécution distante)
    - name: Exécuter une commande sur le serveur distant via SSH
      ansible.builtin.shell: "echo 'Connecting to Vault and retrieving secrets...'"
      delegate_to: "{{ ssh_host }}"
