- name: Vérifier le statut du job Jenkins et gérer les interfaces Proxmox
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Récupérer les secrets depuis Vault (KV v2)
      community.hashi_vault.vault_read:
        path: "secret/data/datajenkins_proxmox1"  # Chemin correct pour récupérer les secrets
        url: "{{ lookup('ansible.builtin.env', 'VAULT_ADDR') }}"
        token: "{{ lookup('env', 'VAULT_TOKEN') }}"  # Utilisation du token Vault depuis l'environnement
      register: secrets

    - name: Afficher le contenu brut des secrets récupérés
      debug:
        var: secrets

    - name: Définir les variables sensibles à partir de Vault
      set_fact:
        jenkins_user: "{{ secrets.data.data.data.jenkins_user }}"
        jenkins_api_token: "{{ secrets.data.data.data.jenkins_api_token }}"
        jenkins_url: "{{ secrets.data.data.data.jenkins_url }}"
        job_name: "{{ secrets.data.data.data.job_name }}"
        proxmox_host: "{{ secrets.data.data.data.proxmox_host }}"
        proxmox_node: "{{ secrets.data.data.data.proxmox_node }}"

    - name: Afficher les variables sensibles définies
      debug:
        msg:
          - "Jenkins User : {{ jenkins_user }}"
          - "Jenkins API Token : {{ jenkins_api_token }}"
          - "Jenkins URL : {{ jenkins_url }}"
          - "Job Name : {{ job_name }}"
          - "Proxmox Host : {{ proxmox_host }}"
          - "Proxmox Node : {{ proxmox_node }}"

    - name: Obtenir le statut du log du job Jenkins
      uri:
        url: "{{ jenkins_url }}/job/{{ job_name | urlencode }}/lastBuild/consoleText/api/json"
        method: GET
        return_content: yes
        status_code: 200
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_api_token }}"
        force_basic_auth: yes
      register: jenkins_response

    - name: Vérifier si le job a réussi
      set_fact:
        job_success: "{{ 'Finished: SUCCESS' in jenkins_response.content }}"

    - name: Afficher le statut du job Jenkins
      debug:
        msg: "Le job Jenkins '{{ job_name }}' a {% if job_success %}réussi{% else %}échoué{% endif %}."



