---
- name: Vérifier le statut du job Jenkins et gérer les interfaces Proxmox
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Récupérer les secrets depuis Vault (KV v2)
      community.hashi_vault.vault_read:
        path: "secret/data/data/jenkins_proxmox2"  # Chemin correct pour récupérer les secrets
        url: "http://10.10.150.2:8200"  # URL de votre serveur Vault
        token: "{{ lookup('env', 'VAULT_TOKEN') }}"  # Utilisation du token Vault depuis l'environnement
      register: secrets

    - name: Afficher le contenu brut des secrets récupérés
      debug:
        var: secrets

    - name: Définir les variables sensibles à partir de Vault
      set_fact:
        jenkins_url: "{{ secrets.data.data.data.jenkins_url }}"
        job_name: "{{ secrets.data.data.data.job_name }}"
        jenkins_user: "{{ secrets.data.data.data.jenkins_user }}"
        jenkins_api_token: "{{ secrets.data.data.data.jenkins_api_token }}"
        proxmox_host: "{{ secrets.data.data.data.proxmox_host }}"
        proxmox_node: "{{ secrets.data.data.data.proxmox_node }}"

    - name: Afficher les variables sensibles définies
      debug:
        msg:
          - "Jenkins URL : {{ jenkins_url }}"
          - "Job Name : {{ job_name }}"
          - "Jenkins User : {{ jenkins_user }}"
          - "Jenkins API Token : {{ jenkins_api_token }}"
          - "Proxmox Host : {{ proxmox_host }}"
          - "Proxmox Node : {{ proxmox_node }}"

    - name: Obtenir le statut du log du job Jenkins
      uri:
        url: "{{ jenkins_url }}/job/{{ job_name | urlencode }}/lastBuild/consoleText/api/json"
        method: GET
        return_content: yes
        status_code: 200
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_api_token }}"
        force_basic_auth: yes
      register: jenkins_response

    - name: Vérifier si le job a réussi
      set_fact:
        job_success: "{{ 'Finished: SUCCESS' in jenkins_response.content }}"

    - name: Afficher le statut du job Jenkins
      debug:
        msg: "Le job Jenkins '{{ job_name }}' a {% if job_success %}réussi{% else %}échoué{% endif %}."

    - name: Gérer les erreurs spécifiques si le job échoue
      when: not job_success
      block:
        - name: Vérifier l'erreur 'interface already exists'
          set_fact:
            interface_error: "{{ 'interface already exists' in jenkins_response.content }}"

        - name: Afficher l'erreur spécifique si elle existe
          debug:
            msg: "Le job a échoué car des interfaces existent déjà sur le serveur Proxmox."
          when: interface_error

        - name: Suggérer des actions correctives si nécessaire
          debug:
            msg:
              Les interfaces existantes doivent être corrigées sur Proxmox.
              Relancez ensuite le job Jenkins.
          when: interface_error

    - name: Afficher un message de succès si le job réussit
      debug:
        msg:
          Le job Jenkins a réussi et aucune action supplémentaire n'est nécessaire.
      when:
        job_success
